
import type { QuizQuestion, Pet } from "./types";

export const sampleQuestions: QuizQuestion[] = [
  // General Education
  {
    id: 1,
    category: "gen_education",
    difficulty: "easy",
    question: "What is the capital of the Philippines?",
    choices: ["Manila", "Quezon City", "Cebu City", "Davao City"],
    answer: "Manila",
    explanation: "Manila was declared the capital of the Philippines in 1571.",
  },
  {
    id: 2,
    category: "gen_education",
    difficulty: "easy",
    question: "Who is the national hero of the Philippines?",
    choices: ["Jose Rizal", "Andres Bonifacio", "Emilio Aguinaldo", "Apolinario Mabini"],
    answer: "Jose Rizal",
    explanation: "Jose Rizal is widely considered the greatest Filipino hero.",
  },
  {
    id: 3,
    category: "gen_education",
    difficulty: "medium",
    question: "What is the longest river in the Philippines?",
    choices: ["Cagayan River", "Pasig River", "Mindanao River", "Agusan River"],
    answer: "Cagayan River",
    explanation: "The Cagayan River, also known as the Rio Grande de Cagayan, is the longest river in the Philippines.",
  },
  {
    id: 4,
    category: "gen_education",
    difficulty: "hard",
    question: "The 'Cry of Pugad Lawin' marked the start of what historical event?",
    choices: ["Philippine Revolution", "EDSA Revolution", "Battle of Mactan", "Fall of Bataan"],
    answer: "Philippine Revolution",
    explanation: "It was the beginning of the Philippine Revolution against Spanish rule in 1896.",
  },
  {
    id: 5,
    category: "gen_education",
    difficulty: "medium",
    question: "What is the chemical symbol for Gold?",
    choices: ["Au", "Ag", "Go", "Gd"],
    answer: "Au",
    explanation: "Au comes from the Latin word for gold, 'aurum'.",
  },
  {
    id: 11,
    category: "gen_education",
    difficulty: "easy",
    question: "How many islands are there in the Philippines?",
    choices: ["7,107", "7,641", "7,890", "7,412"],
    answer: "7,641",
    explanation: "The official count of islands in the Philippine archipelago is 7,641.",
  },
  {
    id: 12,
    category: "gen_education",
    difficulty: "medium",
    question: "Who was the first president of the Philippines?",
    choices: ["Manuel Quezon", "Emilio Aguinaldo", "Jose P. Laurel", "Sergio Osmeña"],
    answer: "Emilio Aguinaldo",
    explanation: "Emilio Aguinaldo was the first president of the First Philippine Republic.",
  },
  {
    id: 13,
    category: "gen_education",
    difficulty: "hard",
    question: "Which Philippine volcano is famous for its perfect cone shape?",
    choices: ["Mount Pinatubo", "Taal Volcano", "Mayon Volcano", "Mount Apo"],
    answer: "Mayon Volcano",
    explanation: "Mayon Volcano in Albay province is renowned for its symmetrical, conical shape.",
  },

  // Professional Education
  {
    id: 6,
    category: "professional",
    difficulty: "easy",
    question: "Which educational philosophy emphasizes the importance of student-centered learning?",
    choices: ["Progressivism", "Essentialism", "Perennialism", "Existentialism"],
    answer: "Progressivism",
    explanation: "Progressivism believes that education should focus on the whole child, rather than on the content or the teacher.",
  },
  {
    id: 7,
    category: "professional",
    difficulty: "medium",
    question: "What is the highest level in Bloom's Taxonomy (original version)?",
    choices: ["Evaluation", "Synthesis", "Analysis", "Application"],
    answer: "Evaluation",
    explanation: "In the original taxonomy, the levels are Knowledge, Comprehension, Application, Analysis, Synthesis, and Evaluation.",
  },
  {
    id: 8,
    category: "professional",
    difficulty: "hard",
    question: "What does the 'Zone of Proximal Development' (ZPD) by Lev Vygotsky refer to?",
    choices: [
        "The difference between what a learner can do without help and what they can achieve with guidance.",
        "The area in the classroom where students feel most comfortable.",
        "The level of knowledge a student is expected to have at a certain age.",
        "A method for assessing student intelligence."
    ],
    answer: "The difference between what a learner can do without help and what they can achieve with guidance.",
    explanation: "ZPD is a key concept in Vygotsky's sociocultural theory of learning.",
  },
  {
    id: 9,
    category: "professional",
    difficulty: "medium",
    question: "RA 7836 is also known as the...",
    choices: [
        "Philippine Teachers Professionalization Act of 1994",
        "Code of Ethics for Professional Teachers",
        "Magna Carta for Public School Teachers",
        "The Enhanced Basic Education Act of 2013"
    ],
    answer: "Philippine Teachers Professionalization Act of 1994",
    explanation: "This act strengthened the regulation and supervision of the practice of teaching in the Philippines.",
  },
  {
    id: 10,
    category: "professional",
    difficulty: "easy",
    question: "What type of assessment is conducted at the end of a unit to measure student learning?",
    choices: ["Summative Assessment", "Formative Assessment", "Diagnostic Assessment", "Authentic Assessment"],
    answer: "Summative Assessment",
    explanation: "Summative assessments are used to evaluate student learning, skill acquisition, and academic achievement at the conclusion of a defined instructional period.",
  },
  {
    id: 14,
    category: "professional",
    difficulty: "medium",
    question: "Which learning theory suggests that people learn from one another, via observation, imitation, and modeling?",
    choices: ["Social Learning Theory", "Behaviorism", "Cognitivism", "Constructivism"],
    answer: "Social Learning Theory",
    explanation: "Albert Bandura's Social Learning Theory posits that learning is a cognitive process that takes place in a social context.",
  },
  {
    id: 15,
    category: "professional",
    difficulty: "easy",
    question: "Which of the following is a primary role of a teacher in a constructivist classroom?",
    choices: ["Facilitator", "Lecturer", "Instructor", "Dictator"],
    answer: "Facilitator",
    explanation: "In constructivism, the teacher acts as a facilitator who guides students as they construct their own knowledge.",
  },
  {
    id: 16,
    category: "professional",
    difficulty: "hard",
    question: "A teacher uses a portfolio to assess a student's progress over a period. What type of assessment is this?",
    choices: ["Authentic Assessment", "Summative Assessment", "Norm-referenced Assessment", "Criterion-referenced Assessment"],
    answer: "Authentic Assessment",
    explanation: "Authentic assessment involves tasks that are relevant to the students' lives and experiences, such as creating a portfolio.",
  }
];

export const pets: Pet[] = [
    { name: "Pet Rock", unlock_criteria: "1-day streak", streak_req: 1, image: "https://placehold.co/200x200", hint: "rock stone" },
    { name: "Goldfish", unlock_criteria: "3-day streak", streak_req: 3, image: "https://placehold.co/200x200", hint: "goldfish fishbowl" },
    { name: "Turtle", unlock_criteria: "7-day streak", streak_req: 7, image: "https://placehold.co/200x200", hint: "sea turtle" },
    { name: "Corgi", unlock_criteria: "14-day streak", streak_req: 14, image: "https://placehold.co/200x200", hint: "cute dog" },
    { name: "Owl", unlock_criteria: "21-day streak", streak_req: 21, image: "https://placehold.co/200x200", hint: "wise owl" },
    { name: "Panda", unlock_criteria: "30-day streak", streak_req: 30, image: "https://placehold.co/200x200", hint: "panda eating" },
    { name: "T-Rex", unlock_criteria: "50-day streak", streak_req: 50, image: "https://placehold.co/200x200", hint: "dinosaur rex" },
    { name: "Dragon", unlock_criteria: "75-day streak", streak_req: 75, image: "https://placehold.co/200x200", hint: "fantasy dragon" },
    { name: "Phoenix", unlock_criteria: "100-day streak", streak_req: 100, image: "https://placehold.co/200x200", hint: "fire bird" },
];
