
import type { QuizQuestion, Pet } from "./types";

export const sampleQuestions: QuizQuestion[] = [
  {
    id: 1,
    category: "gen_education",
    difficulty: "easy",
    question: "Rennie Boy believes that everything that happens in this world has a cause or a reason. What scientific attitude is seen in his actions?",
    choices: ["curiosity", "firm set of beliefs", "honesty", "critical-mindedness"],
    answer: "firm set of beliefs",
  },
  {
    id: 2,
    category: "gen_education",
    difficulty: "medium",
    question: "_____ it never recycled any waste materials, the company’s environmental record was not perfect.",
    choices: ["For", "In that", "With", "Due to"],
    answer: "In that",
  },
  {
    id: 3,
    category: "gen_education",
    difficulty: "hard",
    question: "Our guest of honor was a loquacious speaker. Loquacious means:",
    choices: ["reserved", "verbose", "reticent", "spiritless"],
    answer: "verbose",
  },
  {
    id: 4,
    category: "gen_education",
    difficulty: "easy",
    question: "The sociological concept of home for most Filipino is the presence of _____.",
    choices: ["families with boarders in addition to the family members", "nuclear family and extended families", "families with illegal light and water connections", "families with pet dogs and cats"],
    answer: "nuclear family and extended families",
  },
  {
    id: 5,
    category: "gen_education",
    difficulty: "medium",
    question: '"A man is known by the company he keeps." This is an example of a _____.',
    choices: ["report", "rule", "poem", "proverb"],
    answer: "proverb",
  },
  {
    id: 6,
    category: "gen_education",
    difficulty: "hard",
    question: "Which of the following is the ultimate purpose of Human Right Education?",
    choices: ["to identify threats of human rights", "to generate awareness of one’s basic rights", "to check on abuses in the exercise of human rights", "to understand and change conditions which give rise to human rights violation"],
    answer: "to generate awareness of one’s basic rights",
  },
  {
    id: 7,
    category: "gen_education",
    difficulty: "easy",
    question: "The members of the federation of cooperatives are _____.",
    choices: ["primaries", "secondaries", "natural persons", "primary and secondary cooperatives"],
    answer: "primary and secondary cooperatives",
  },
  {
    id: 8,
    category: "gen_education",
    difficulty: "medium",
    question: "Be sure to fill _____ the forms correctly.",
    choices: ["over", "in", "on", "with"],
    answer: "in",
  },
  {
    id: 9,
    category: "gen_education",
    difficulty: "hard",
    question: "Vascular tissue that transports water in leaves connects directly to which of the following?",
    choices: ["meristems in the root tip", "pistils in the flower", "root hairs in the epidermis", "xylem in the stem"],
    answer: "xylem in the stem",
  },
  {
    id: 10,
    category: "gen_education",
    difficulty: "easy",
    question: "Which statement is true?",
    choices: ["5–√ is a rational number.", "0 is a positive number", "3–√ is a real number.", "4–√ is an irrational number"],
    answer: "3–√ is a real number.",
  },
  {
    id: 11,
    category: "gen_education",
    difficulty: "medium",
    question: "If a die is rolled, what is the probability of getting a number divisible by 2?",
    choices: ["1/6", "1/2", "1/4", "1/3"],
    answer: "1/2",
  },
  {
    id: 12,
    category: "gen_education",
    difficulty: "hard",
    question: "Why do mothers usually soak meat in pineapple juice before cooking it?",
    choices: ["It makes meat tender.", "It removes the bad odor.", "It improves the taste of meat.", "It preserves the natural taste of meat."],
    answer: "It makes meat tender.",
  },
  {
    id: 13,
    category: "gen_education",
    difficulty: "easy",
    question: "What is considered the earliest form of writing in the Philippines?",
    choices: ["Abakada", "Roman alphabet", "Alibata", "Balitaw"],
    answer: "Alibata",
  },
  {
    id: 14,
    category: "gen_education",
    difficulty: "medium",
    question: "Most asteroids are found between the two planets:",
    choices: ["Venus and Earth", "Earth and Mars", "Mars and Jupiter", "Jupiter and Saturn"],
    answer: "Mars and Jupiter",
  },
  {
    id: 15,
    category: "gen_education",
    difficulty: "hard",
    question: "A wood frame for pouring concrete has an interior perimeter of 14 meters. Its length is one meter greater than its width. The frame is to be braced with twelve-gauge steel cross-wires. Assuming an extra half-meter of wire is used at either end of a cross-wire for anchoring, what length of wire should be cut for each brace?",
    choices: ["6 m", "7 m", "8 m", "12 m"],
    answer: "6 m",
  },
  {
    id: 16,
    category: "gen_education",
    difficulty: "easy",
    question: "New students at the shop should bring _____.",
    choices: ["hammers wrenches and screwdrivers", "hammers, wrenches, and screwdrivers", "hammers, wrenches and screwdrivers", "hammers wrenches, and screwdrivers"],
    answer: "hammers, wrenches, and screwdrivers",
  },
  {
    id: 17,
    category: "gen_education",
    difficulty: "medium",
    question: "The army’s retreat was IGNOMINICUSFUL. This means _____.",
    choices: ["reputable", "honorable", "shameful", "mysterious"],
    answer: "shameful",
  },
  {
    id: 18,
    category: "gen_education",
    difficulty: "hard",
    question: "Ibigay ang tayutay na nagamit sa sumusunod: Ikaw ang payong ng aking buhay - silungan ng init - hatid ay proteksyon sa panahong masungit",
    choices: ["simile", "personipikasyon", "metapora", "paglilipat-wika"],
    answer: "metapora",
  },
  {
    id: 19,
    category: "gen_education",
    difficulty: "easy",
    question: "Which of the following BEST demonstrates the greenhouse principle?",
    choices: ["a heated aquarium", "a car with rolled-up windows", "a microwave oven", "a solar battery -powered calculator"],
    answer: "a car with rolled-up windows",
  },
  {
    id: 20,
    category: "gen_education",
    difficulty: "medium",
    question: "The bank was swarmed with depositors. The bank ______",
    choices: ["declared an open house", "declared dividends", "declared a holiday", "declared bankruptcy"],
    answer: "declared bankruptcy",
  },
  {
    id: 21,
    category: "gen_education",
    difficulty: "hard",
    question: "The Rizal Day celebration reminds us about heroes worth _____.",
    choices: ["appreciating", "emulating", "reading about", "studying"],
    answer: "emulating",
  },
  {
    id: 22,
    category: "gen_education",
    difficulty: "easy",
    question: "Which among the following represents the smallest unit of life?",
    choices: ["embryo", "organelle", "cell", "atom"],
    answer: "cell",
  },
  {
    id: 23,
    category: "gen_education",
    difficulty: "medium",
    question: "What is the equation of the line whose slope is -2 and whose y-intercept is 3?",
    choices: ["2x +3y =6", "x +2y =3", "2x +2y =4", "2x +y =3"],
    answer: "2x +y =3",
  },
  {
    id: 24,
    category: "gen_education",
    difficulty: "hard",
    question: "Nag-aaral ako _____ mabuti upang makakuha ako ng iskolarship.",
    choices: ["nang", "ng", "mas", "lalong"],
    answer: "nang",
  },
  {
    id: 25,
    category: "gen_education",
    difficulty: "easy",
    question: "Two air masses have the same humidity. Which of the following can also be said about them?",
    choices: ["They have the same temperature.", "They have the same volume", "Both have rain clouds.", "none of the above"],
    answer: "none of the above",
  },
  {
    id: 26,
    category: "gen_education",
    difficulty: "medium",
    question: "_____ I help you, sir?",
    choices: ["Might", "Could", "May", ""],
    answer: "May",
  },
  {
    id: 27,
    category: "gen_education",
    difficulty: "hard",
    question: "What measure of central tendency can best describe the size of t-shirts commonly used by teenagers?",
    choices: ["mean", "median", "mode", "both a and c"],
    answer: "mode",
  },
  {
    id: 28,
    category: "gen_education",
    difficulty: "easy",
    question: "_____ tell her professor next time.",
    choices: ["She does", "She", "She'll", "She's"],
    answer: "She'll",
  },
  {
    id: 29,
    category: "gen_education",
    difficulty: "medium",
    question: "Wise people can _____ with frustrations.",
    choices: ["cope in", "cope up", "cope", "cope on"],
    answer: "cope",
  },
  {
    id: 30,
    category: "gen_education",
    difficulty: "hard",
    question: "Which enables the computer to communicate with other computers over the telephone?",
    choices: ["network", "modem", "internet", "hypermedia"],
    answer: "modem",
  },
  {
    id: 31,
    category: "gen_education",
    difficulty: "easy",
    question: "Which of the following is expressed clearly, effectively states the idea, and has no structural error?",
    choices: ["I learned the distance of the sun from the earth was 90 million miles.", "I learned that the sun was 90 million miles from the earth.", "I learned that the sun is 90 million miles from the earth.", "I learned that the earth and the sun are 90 million miles apart."],
    answer: "I learned that the sun is 90 million miles from the earth.",
  },
  {
    id: 32,
    category: "gen_education",
    difficulty: "medium",
    question: "Basically, the Philippine agrarian reform is a question of _____.",
    choices: ["land distribution", "nepotism and corruption", "graft and corruption", "environmental degradation"],
    answer: "land distribution",
  },
  {
    id: 33,
    category: "gen_education",
    difficulty: "hard",
    question: "I really object _____ in rooms where other people have to eat.",
    choices: ["people smoking", "to people smoke", "people to smoke", "to people smoking"],
    answer: "to people smoking",
  },
  {
    id: 34,
    category: "gen_education",
    difficulty: "easy",
    question: "What is the exact date of Rizal’s birth?",
    choices: ["June 19, 1862", "June 19, 1858", "June 19, 1861", "June 19, 1860"],
    answer: "June 19, 1861",
  },
  {
    id: 35,
    category: "gen_education",
    difficulty: "medium",
    question: "Given the following scores of 70, 95, 60, 80, and 100, what can you infer from the measures of variability that can be obtained from this?",
    choices: ["The population is very homogeneous.", "The measures are very unstable.", "The grades are very scattered.", "The range of scores is a very reliable measure of variability."],
    answer: "The grades are very scattered.",
  },
  {
    id: 36,
    category: "gen_education",
    difficulty: "hard",
    question: "Which one of the following is a result of compressing a file?",
    choices: ["The file is deleted.", "The file size is smaller.", "The three character extension is hidden.", "All file properties are lost."],
    answer: "The file size is smaller.",
  },
  {
    id: 37,
    category: "gen_education",
    difficulty: "easy",
    question: "What is the measure of an interior angle of a regular dodecagon?",
    choices: ["120 degrees", "130 degrees", "140 degrees", "150 degrees"],
    answer: "150 degrees",
  },
  {
    id: 38,
    category: "gen_education",
    difficulty: "medium",
    question: "1/5 of the width and 1/4 of the length of a rectangular cardboard is cut off. What part of the original cardboard is the area of the remaining piece?",
    choices: ["30% of the original area", "40% of the original area", "50% of the original area", "60% of the original area"],
    answer: "60% of the original area",
  },
  {
    id: 39,
    category: "gen_education",
    difficulty: "hard",
    question: 'Which is the "brain" of a computer?',
    choices: ["CPU", "peripheral", "software", "RAM"],
    answer: "CPU",
  },
  {
    id: 40,
    category: "gen_education",
    difficulty: "easy",
    question: "Which one of the following is an appropriate routine to shut down a non-responding application?",
    choices: ["Close all open documents and press the power button until the computer automatically switches off.", 'Press "Ctrl + Alt + Delete", then select the non responding application in the Task Manager window and click "End Task".', "Pull out the power cable from the back of the computer.", 'Click "Shut Down" on the on the Start menu and choose "Shut down" from the Shut Down Windows drop-down list.'],
    answer: 'Press "Ctrl + Alt + Delete", then select the non responding application in the Task Manager window and click "End Task".',
  },
  {
    id: 41,
    category: "gen_education",
    difficulty: "medium",
    question: "Why do fisherfolks catch more fish during the new moon than during the full moon?",
    choices: ["Fishes are more active during the new moon because of the salt content of water is just right.", "Fishes look for mates during the new moon.", "Fishes go near the surface during the new moon because the water is warmer.", "Fishes are attracted to the light from the fishing boat which fishermen make use during the new moon."],
    answer: "Fishes are attracted to the light from the fishing boat which fishermen make use during the new moon.",
  },
  {
    id: 42,
    category: "gen_education",
    difficulty: "hard",
    question: '"Mahal kita, mahal kita, hindi \'to bola/ Ngumiti ka man lang sana ako\'y nasa langit na." Ang salitang pampanitikan na ginamit sa linya ng kanta ay nangangahulugang _____.',
    choices: ["napakasaya", "pakikipagkaibigan", "sinisinta", "laruan"],
    answer: "napakasaya",
  },
  {
    id: 43,
    category: "gen_education",
    difficulty: "easy",
    question: "Which is the method of growing vegetables and low plants in a nutrient-packed aerated solution with no soil at all?",
    choices: ["vegetative cultivation", "natural farming", "hydroponics", "aerial cultivation"],
    answer: "hydroponics",
  },
  {
    id: 44,
    category: "gen_education",
    difficulty: "medium",
    question: "Which part of the brain is responsible for memory and intelligence?",
    choices: ["cerebellum", "cerebrum", "medulla oblongata", "thalamus"],
    answer: "cerebrum",
  },
  {
    id: 45,
    category: "gen_education",
    difficulty: "hard",
    question: "How can the Comprehensive Agrarian Reform Program bring about social equity and economic prosperity in the country?",
    choices: ["By distributing the agricultural lands to landless farmers free of charge", "By transferring the ownership of land to farmers for a value", "By helping the affected landowners to use their land compensation in viable business activities", "By providing support services to farmer beneficiaries"],
    answer: "By transferring the ownership of land to farmers for a value",
  },
  {
    id: 46,
    category: "gen_education",
    difficulty: "easy",
    question: "You are a member of a cooperative which operates taxis, tricycles, and buses. Of which type of a cooperative are you a member?",
    choices: ["service cooperative", "multipurpose cooperative", "marketing cooperative", "producers cooperative"],
    answer: "service cooperative",
  },
  {
    id: 47,
    category: "gen_education",
    difficulty: "medium",
    question: "Which among the following is an example of a transfer payment?",
    choices: ["profit", "rent", "unemployment benefits", "government purchases"],
    answer: "unemployment benefits",
  },
  {
    id: 48,
    category: "gen_education",
    difficulty: "hard",
    question: "Adolfo does not allow his feelings and biases to influence his recording of observations, interpretation of data, and formulation of conclusions. What scientific attitude is reflected in his actions?",
    choices: ["absence of bias", "concern for the environment", "rationality", "objectivity"],
    answer: "objectivity",
  },
  {
    id: 49,
    category: "gen_education",
    difficulty: "easy",
    question: "If a baseball player hits 10 home runs in the first 45 games, at the same rate how many home runs can he expect to hit during the 162-game season?",
    choices: ["38", "42", "36", "40"],
    answer: "36",
  },
  {
    id: 50,
    category: "gen_education",
    difficulty: "medium",
    question: "Which method of reproduction provides for the most variety of offspring?",
    choices: ["cloning", "sexual reproduction", "asexual reproduction", "cellular reproduction"],
    answer: "sexual reproduction",
  },
  {
    id: 51,
    category: "gen_education",
    difficulty: "hard",
    question: "The following EXCEPT one are experience that help students build a global orientation.",
    choices: ["Teach about the United Nations and its specialized agencies", "Explore some of the reasons for the differences in ways of living", "Conduct training with schools from other countries", "Promote the development of stereotypes and ethnic bias"],
    answer: "Promote the development of stereotypes and ethnic bias",
  },
  {
    id: 52,
    category: "gen_education",
    difficulty: "easy",
    question: "Alin ang paksa sa sumusunod na pangungusap? Ginagawa niya ang pagdarasal araw-araw.",
    choices: ["ginagawa", "araw-araw", "pagdarasal", "niya"],
    answer: "pagdarasal",
  },
  {
    id: 53,
    category: "gen_education",
    difficulty: "medium",
    question: "What instrument is used to measure the intensity of earthquakes?",
    choices: ["barograph", "thermograph", "seismograph", "hygrograph"],
    answer: "seismograph",
  },
  {
    id: 54,
    category: "gen_education",
    difficulty: "hard",
    question: "Excuse me, can I borrow _____ dictionary?",
    choices: ["your", "yours", "you", "a"],
    answer: "your",
  },
  {
    id: 55,
    category: "gen_education",
    difficulty: "easy",
    question: "Alin ang di karaniwang anyo ng pandiwang HINTAY KA?",
    choices: ["tay", "tayka", "intay", "teka"],
    answer: "tayka",
  },
  {
    id: 56,
    category: "gen_education",
    difficulty: "medium",
    question: "Alin sa mga sumusunod ang aral na ibinigay ng ANG ALAMAT NI MARIANG MAKILlNG na ikinuwento ni Jose Rizal?",
    choices: ["Pagyamanin at pangalagaan ang ating bayan at lahi pagka’t hiyas at yaman natin ito.", "Pag-ibig ang makapagbabago sa mundong ito.", "Kabanalan ang magpatawad at tulungan ang isang nagkasala.", "Dahil sa pagmamalabis at pagsasamantala, maraming biyaya ang sa kanya'y nawawala."],
    answer: "Dahil sa pagmamalabis at pagsasamantala, maraming biyaya ang sa kanya'y nawawala.",
  },
  {
    id: 57,
    category: "gen_education",
    difficulty: "hard",
    question: "Which is the main goal of drug abuse education?",
    choices: ["arrest", "prevention", "control", "rehabilitation"],
    answer: "prevention",
  },
  {
    id: 58,
    category: "gen_education",
    difficulty: "easy",
    question: "The amount of substance having 6.02 x 10^23 of any kind of chemical unit is called a/an _____.",
    choices: ["mass number", "mole", "formula", "atomic weight"],
    answer: "mole",
  },
  {
    id: 59,
    category: "gen_education",
    difficulty: "medium",
    question: "How many ways can a committee of 4 people be selected from a group of 7 people?",
    choices: ["35", "70", "140", "210"],
    answer: "35",
  },
  {
    id: 60,
    category: "gen_education",
    difficulty: "hard",
    question: "A rectangle is 4 times a long as it is wide. If the length of the third side?",
    choices: ["2 x 32", "4 x 16", "3 x 14", "5 x 12"],
    answer: "4 x 16",
  },
  {
    id: 61,
    category: "gen_education",
    difficulty: "easy",
    question: "What law was passed by Philippine Congress in 1995 which affirms the total integration of persons with disabilities into the mainstream of society?",
    choices: ["R.A. 7277", "R.A. 7784", "R.A. 7722", "R.A. 7776"],
    answer: "R.A. 7277",
  },
  {
    id: 62,
    category: "gen_education",
    difficulty: "medium",
    question: "Far _____ Terry’s small plane lay the freezing waters of the North Sea, where his father’s boat had disappeared many years before.",
    choices: ["down", "under", "underneath", "below"],
    answer: "below",
  },
  {
    id: 63,
    category: "gen_education",
    difficulty: "hard",
    question: "To reduce electronic waste, implement a recycling system. Which belong to an e-waste recycling system?",
    choices: ["Repair", "Reuse", "Upgrading of existing equipment"],
    answer: "Repair",
  },
  {
    id: 64,
    category: "gen_education",
    difficulty: "easy",
    question: "A molecule or an ion is classified as a Lewis base if it has which of the following properties?",
    choices: ["donates a proton to water", "accepts a pair of electrons", "has resonance structures", "accepts a proton from water"],
    answer: "accepts a proton from water",
  },
  {
    id: 65,
    category: "gen_education",
    difficulty: "medium",
    question: "Kailan natin ipinadiriwang ang Lingo ng Wika?",
    choices: ["Hunyo 13-19", "Agosto 13-19", "Agosto 1-31", "Marso 13-19"],
    answer: "Agosto 13-19",
  },
  {
    id: 66,
    category: "gen_education",
    difficulty: "hard",
    question: "Excuse me, _____ the time?",
    choices: ["have you", "have you got", "got you", "do you"],
    answer: "have you got",
  },
  {
    id: 67,
    category: "gen_education",
    difficulty: "easy",
    question: "Nowadays, _____ are much better behaved than their parents were at the same age, don’t you think?",
    choices: ["teenagers", "the teenagers", "a teenager", "teen an ager"],
    answer: "teenagers",
  },
  {
    id: 68,
    category: "gen_education",
    difficulty: "medium",
    question: "If x = 1 and y = -2, what is the value of the expression, x22xy−4x+3xy2?",
    choices: ["-9/2", "15/2", "-7/2", "17/4"],
    answer: "-7/2",
  },
  {
    id: 69,
    category: "gen_education",
    difficulty: "hard",
    question: "Which among the following statements is always true?",
    choices: ["The supplement of an angle is acute.", "The complement of an angle is obtuse.", "The complement of any acute angle is acute.", "Two supplementary angles are congruent."],
    answer: "The complement of any acute angle is acute.",
  },
  {
    id: 70,
    category: "gen_education",
    difficulty: "easy",
    question: "A losing senatorial candidate may file a protest against the winner. What body will assume jurisdiction over the case?",
    choices: ["Supreme Court", "Electoral Tribunal", "COMELEC", "Regional Trial Court"],
    answer: "Electoral Tribunal",
  },
  {
    id: 71,
    category: "gen_education",
    difficulty: "medium",
    question: 'Ano ang pormasyon na pantig sa mga titik na "prin" sa salitang prinsesa?',
    choices: ["KKPK", "KKP", "KPK", "KP"],
    answer: "KKPK",
  },
  {
    id: 72,
    category: "gen_education",
    difficulty: "hard",
    question: "The Philippines belong to the type of biome called _____.",
    choices: ["dicidous forest", "taiga", "tropical rainforest", "grassland"],
    answer: "tropical rainforest",
  },
  {
    id: 73,
    category: "gen_education",
    difficulty: "easy",
    question: "A square has an area of 400 sq. cm . What is its perimeter?",
    choices: ["20 cm", "80 cm", "100 cm", "40 cm"],
    answer: "80 cm",
  },
  {
    id: 74,
    category: "gen_education",
    difficulty: "medium",
    question: "If 500 or 25% of a graduating class are girls, how many are graduating?",
    choices: ["2000", "5000", "10000", "20000"],
    answer: "2000",
  },
  {
    id: 75,
    category: "gen_education",
    difficulty: "hard",
    question: "What type of thermo-nuclear reaction occurs in the sun which generates a tremendous amount of heat energy?",
    choices: ["fission", "radiation", "convection", "fusion"],
    answer: "fusion",
  },
  {
    id: 76,
    category: "gen_education",
    difficulty: "easy",
    question: "Nobel Prize winners are chosen from different levels. Where was Pres. Quirino considered?",
    choices: ["politics", "literature", "human rights", "economics"],
    answer: "economics",
  },
  {
    id: 77,
    category: "gen_education",
    difficulty: "medium",
    question: "Organisms that eat plants only are called _____.",
    choices: ["ovipores", "herbivores", "omnivores", "carnivores"],
    answer: "herbivores",
  },
  {
    id: 78,
    category: "gen_education",
    difficulty: "hard",
    question: "Piliin ang salitang may diptonggo.",
    choices: ["yoyong", "kamay", "lawa", "tihaya"],
    answer: "kamay",
  },
  {
    id: 79,
    category: "gen_education",
    difficulty: "easy",
    question: "How many prime numbers are there between 1 and 100?",
    choices: ["23", "24", "25", "26"],
    answer: "25",
  },
  {
    id: 80,
    category: "gen_education",
    difficulty: "medium",
    question: "You cannot share what you do not have, Who portrayed it best?",
    choices: ["Heaven is built on stilts. One can buy all happiness.", "The Man scorned on the Cross not redeem the world without suffering.", "Patience on the rice store cue was tested by a grumbling lady.", "Words without deeds can never go far."],
    answer: "The Man scorned on the Cross not redeem the world without suffering.",
  },
  {
    id: 81,
    category: "gen_education",
    difficulty: "hard",
    question: "When a person shows the ability to understand and appreciate the similarities and differences in the customs, values, and beliefs of one's culture, that person is said to _____.",
    choices: ["possess multicultural literacy", "possess sociocultural awareness", "possess global awareness", "possess social literacy"],
    answer: "possess multicultural literacy",
  },
  {
    id: 82,
    category: "gen_education",
    difficulty: "easy",
    question: "Mr. Lucido deposited 225 pesos in the bank. If his deposit consisted of 29 bills, consisting of 5 peso, and 10 peso bills, how many 10 peso bills did he deposit?",
    choices: ["13", "14", "15", "16"],
    answer: "16",
  },
  {
    id: 83,
    category: "gen_education",
    difficulty: "medium",
    question: "Marumi ang baso. Huwag mong ____ yan!",
    choices: ["inumin", "inuman", "uminom", "pag-inuman"],
    answer: "inuman",
  },
  {
    id: 84,
    category: "gen_education",
    difficulty: "hard",
    question: "When you carry a heavy load with one arm, you tend to hold your free had away from your body in order to _____.",
    choices: ["change the weight of your body and load", "change the mass of your body", "be ready to grab something in case you fall", "change the center of gravity of your body and load"],
    answer: "change the center of gravity of your body and load",
  },
  {
    id: 85,
    category: "gen_education",
    difficulty: "easy",
    question: "If a picture frame is 27 cm long and 18 cm wide, what is the ratio of its length to its width?",
    choices: ["3:2", "2:3", "3:5", "5:3"],
    answer: "3:2",
  },
  {
    id: 86,
    category: "gen_education",
    difficulty: "medium",
    question: "When a teacher is charged with administrative case committed in the lawful discharge of professional duties, what right may the teacher invoke for their defense?",
    choices: ["right to receive compensation in the duration of the case", "right to be given the due process of law", "right to be defended by the organization of teachers to which they are a member", "right to be provided with free legal service by the appropriate office"],
    answer: "right to be provided with free legal service by the appropriate office",
  },
  {
    id: 87,
    category: "gen_education",
    difficulty: "hard",
    question: "In how many ways can a team of 10 basketball players be chosen from 12 players?",
    choices: ["62", "64", "66", "72"],
    answer: "66",
  },
  {
    id: 88,
    category: "gen_education",
    difficulty: "easy",
    question: "Find m in the proportion m/12 = 30/24.",
    choices: ["3", "15", "20", "25"],
    answer: "3",
  },
  {
    id: 89,
    category: "gen_education",
    difficulty: "medium",
    question: "People who are too _____ are liable to be deceived by unscrupulous individuals.",
    choices: ["wary", "credulous", "cynical", "demanding"],
    answer: "credulous",
  },
  {
    id: 90,
    category: "gen_education",
    difficulty: "hard",
    question: "_____ natin ng mapa si Kenny para hindi siya maligaw.",
    choices: ["Iwan", "Mag-iwan", "Iwanan", "Pag-iwan"],
    answer: "Iwanan",
  },
  {
    id: 91,
    category: "gen_education",
    difficulty: "easy",
    question: "Pinandirihan ni Mico ang aso niyang _____.",
    choices: ["ma-galis", "mag-alis", "magalis", "galis-aso"],
    answer: "magalis",
  },
  {
    id: 92,
    category: "gen_education",
    difficulty: "medium",
    question: "Any individual has the right to question why he is being arrested, and to summon his accusers to court so that due process may be performed. This right is embodied in which of the following?",
    choices: ["reclusion perpetua", "res ipsa loquitur", "prison mayor", "habeas corpus"],
    answer: "habeas corpus",
  },
  {
    id: 93,
    category: "gen_education",
    difficulty: "hard",
    question: "The elevator can carry a maximum load of 605 kg. How many passengers of weight 50.5 kg each can the elevator hold?",
    choices: ["12", "11.9", "11", "10"],
    answer: "11",
  },
  {
    id: 94,
    category: "gen_education",
    difficulty: "easy",
    question: "4 1/5 + 3 2/7 = _____",
    choices: ["7 3/12", "7 3/35", "7 17/35", "7 1/35"],
    answer: "7 3/12",
  },
  {
    id: 95,
    category: "gen_education",
    difficulty: "medium",
    question: "For the fruit punch, 3050 mL of fruit juice is needed. How much fruit juice is needed in dekaliters?",
    choices: ["0.305", "3.05", "5.03", "0.053"],
    answer: "0.305",
  },
  {
    id: 96,
    category: "gen_education",
    difficulty: "hard",
    question: '"Ang babae ay huwag mong tingnang isang bagay na libangan lamang kundi isang katuwang at karamay sa mga kahirapan nitong kabuhayan." (E. Jacinto) Ang tungkulin ng wika sa linya ay _____.',
    choices: ["pangheuristiko", "pang-interaksyunal", "panregulatori", "pang-instrumental"],
    answer: "panregulatori",
  },
  {
    id: 97,
    category: "gen_education",
    difficulty: "easy",
    question: "Anong tayutay ang tinutukoy nito? Durog ang katawang bumagsak sa semento si Miguel.",
    choices: ["pagtutulad", "pagbibigay-katauhan", "pagmamalabis", "pagwawangis"],
    answer: "pagwawangis",
  },
  {
    id: 98,
    category: "gen_education",
    difficulty: "medium",
    question: "Yes, the script was excellent, but the performances were _____ weak.",
    choices: ["completely", "extremely", "utterly", "absolutely"],
    answer: "extremely",
  },
  {
    id: 99,
    category: "gen_education",
    difficulty: "hard",
    question: "The smallest angle of a triangle is two-thirds the size of the middle angle, and the middle angle is three-sevenths of the largest angle. Find all three angle measures.",
    choices: ["30°, 60°, 90°", "45°, 45°, 90°", "35°, 45°, 110°", "30°, 45°, 105°"],
    answer: "30°, 45°, 105°",
  },
  {
    id: 100,
    category: "gen_education",
    difficulty: "easy",
    question: "Tandaan mo na lahat ng paghihirap ni Luis ay _____ sa iyong magandang kinabukasan.",
    choices: ["tungkol", "upang", "sanhi", "ukol"],
    answer: "ukol",
  },
  {
    id: 101,
    category: "gen_education",
    difficulty: "medium",
    question: "Ang mga mata mo ay tulad ng bituin sa kalangitan. Ano ang ginamit na pagpapahayag dito?",
    choices: ["pagtutulad", "personipikasyon", "pagwawangis", "pang-uyam"],
    answer: "pagtutulad",
  },
  {
    id: 102,
    category: "gen_education",
    difficulty: "hard",
    question: "What science deals with the study of outer space?",
    choices: ["Astronomy", "Oceanography", "Paleontology", "Geology"],
    answer: "Astronomy",
  },
  {
    id: 103,
    category: "gen_education",
    difficulty: "easy",
    question: "To pass her English Test, Lucille must get 75% of the items correct. Out of 80 questions, how many must she correctly answer?",
    choices: ["55", "60", "70", "65"],
    answer: "60",
  },
  {
    id: 104,
    category: "gen_education",
    difficulty: "medium",
    question: "To stimulate the nation's economy and to increase employment, former President Diosdado Macapagal _____.",
    choices: ["abolished government repressive controls", "borrowed money from the World Bank", "standardized the salaries of government employees", "gave incentives to home cottage industries"],
    answer: "abolished government repressive controls",
  },
  {
    id: 105,
    category: "gen_education",
    difficulty: "hard",
    question: "The ratio of the number of red, green, and blue balls in a box is 2:5:6. How many green balls are there if there are 52 balls in all?",
    choices: ["4", "8", "20", "24"],
    answer: "20",
  },
  {
    id: 106,
    category: "gen_education",
    difficulty: "easy",
    question: "Which of the following is expressed clearly, effectively states the idea, and has no structural error?",
    choices: ["Good teachers possess a capacity for connectedness; not in the method but in their hearts - a place where intellect, emotion, spirit, and will converge in the human self.", "Good teachers possess a capacity for cooperation; not in the method but in their hearts where they knowledge, spirit and emotion converge.", "Good teachers are capable to promote nterrelationship among learners, parents, school heads, and community.", "Good teachers have the capacity to develop interpersonal relationship among the factors in the learning environment."],
    answer: "Good teachers possess a capacity for connectedness; not in the method but in their hearts - a place where intellect, emotion, spirit, and will converge in the human self.",
  },
  {
    id: 107,
    category: "gen_education",
    difficulty: "medium",
    question: "We’re late. By the time we get to the cinema, the film _____ .",
    choices: ["will have started", "has started", "will start", "will have been starting"],
    answer: "will have started",
  },
  {
    id: 108,
    category: "gen_education",
    difficulty: "hard",
    question: "One of the objectives of Philippine Education as provided in the 1987 Constitutions is to promote respect for human rights. To gave flesh to this constitutional mandate, President Aquino issued an order requiring human rights to be integrated in the school curricula. Which of the following specifies the said directives?",
    choices: ["DECS Order No. 61", "Executive Order No. 27", "Presidential Decree No. 603", "Administrative Order No. 2"],
    answer: "Executive Order No. 27",
  },
  {
    id: 109,
    category: "gen_education",
    difficulty: "easy",
    question: "In which part of the flower develop into seeds?",
    choices: ["pistil", "ovary", "ovules", "ovary wall"],
    answer: "ovules",
  },
  {
    id: 110,
    category: "gen_education",
    difficulty: "medium",
    question: "renewable",
    choices: ["a resource that is inexhaustible", "a process where one plate is forced under another", "the blanket of air surrounding the Earth", "describes how different types of rocks are formed"],
    answer: "a resource that is inexhaustible",
  },
  {
    id: 111,
    category: "gen_education",
    difficulty: "hard",
    question: "Which of the following is expressed clearly, effectively states the idea, and has no structural error?",
    choices: ["Albert himself told me it was true.", "Albert, himself, told me it was true.", "Albert told me it was true himself.", "Albert told me himself it was true."],
    answer: "Albert himself told me it was true.",
  },
  {
    id: 112,
    category: "gen_education",
    difficulty: "easy",
    question: "Did you have _____ on holiday?",
    choices: ["a good weather", "good weathers", "good weather"],
    answer: "good weather",
  },
  {
    id: 113,
    category: "gen_education",
    difficulty: "medium",
    question: "A behavioral psychologist would probably say that _____.",
    choices: ["introspection is a useful way to study mental processes", "the mind is most important when analyzing behavior", "we act based on rewards and punishments received", "the unconsciousness stimulates our behavior"],
    answer: "we act based on rewards and punishments received",
  },
  {
    id: 114,
    category: "gen_education",
    difficulty: "hard",
    question: 'Sino ang naglimbag ng "El Guinto de Pueblo ng panahon ng Amerikano?',
    choices: ["Sergio Osmena", "Pascual Poblete", "Jose Palma", "Francisco Balagtas"],
    answer: "Jose Palma",
  },
  {
    id: 115,
    category: "gen_education",
    difficulty: "easy",
    question: "When two missing digits in a given number are replaced, the number is divisible by 99. What is the number?",
    choices: ["85021", "85031", "85041", "85051"],
    answer: "85041",
  },
  {
    id: 116,
    category: "gen_education",
    difficulty: "medium",
    question: "Which of the following documents embodies the general principles of human rights which set forth the minimum standard of living for all people pf the world?",
    choices: ["International Covenant on Civil, Political Rights", "International Covenant on socio Economic, Cultural rights", "Universal Declaration of Human Rights", "United Nations Declaration on Rights to Development"],
    answer: "United Nations Declaration on Rights to Development",
  },
  {
    id: 117,
    category: "gen_education",
    difficulty: "hard",
    question: "Ibigay ang tayutay na nagamit sa sumusunod: Ilaw ng tahanan - Ikaw ang sandigan - Lamyos ng pagmamahal - Sa pag unlad ko'y tangan",
    choices: ["metonimiya", "sinekdote", "onomatopeya", "pagtawag"],
    answer: "metonimiya",
  },
  {
    id: 118,
    category: "gen_education",
    difficulty: "easy",
    question: "A secret word that must be entered into the computer before a person is allowed access to information is called _____.",
    choices: ["input", "password", "program", "statement"],
    answer: "password",
  },
  {
    id: 119,
    category: "gen_education",
    difficulty: "medium",
    question: "Are you going shopping now? No, but _____ later.",
    choices: ["I might go", "I might to go", "I might going", "I might be go"],
    answer: "I might go",
  },
  {
    id: 120,
    category: "gen_education",
    difficulty: "hard",
    question: "The Code of Ethics of Professional Teachers provides that a teacher has the right and duty to determine the academic marks and the promotion of learners. What is the obligation of the teacher in relation to the aforementioned right as mandated in the Education Act of 1982?",
    choices: ["Refrain from making deductions in students ratings for acts not of poor scholarship.", "Refrain from discriminating high and low achievers in the classes they handle.", "Refrain from influencing corporal punishment and make it a basic for deductions in scholastic ratings.", "Refrain from segregating the fast and slow learners for convenience in rating them."],
    answer: "Refrain from making deductions in students ratings for acts not of poor scholarship.",
  },
  {
    id: 121,
    category: "gen_education",
    difficulty: "easy",
    question: "Which of the following is expressed clearly, effectively states the idea, and has no structural error?",
    choices: ["A strange car kept blinking the lights at us as he followed closely.", "A strange car followed closely, and he kept blinking his lights at us.", "A strange car followed us closely, and its driver kept blinking his lights at us.", "A strange car, blinking the lights at us, followed closely."],
    answer: "A strange car followed us closely, and its driver kept blinking his lights at us.",
  },
  {
    id: 122,
    category: "gen_education",
    difficulty: "medium",
    question: "Which of the following is the catalytic converter on cars in the control technology?",
    choices: ["carbon monoxide", "carbon dioxide", "nitrogen dioxide", "sulfur oxide"],
    answer: "nitrogen dioxide",
  },
  {
    id: 123,
    category: "gen_education",
    difficulty: "hard",
    question: "What type of cooperative provides assistance to general public such as transportation, health and housing?",
    choices: ["consumer", "producer", "credit", "service"],
    answer: "service",
  },
  {
    id: 124,
    category: "gen_education",
    difficulty: "easy",
    question: "Which is at the base of a triangle that shapes us into what we are?",
    choices: ["environment", "heredity", "training", "school attended"],
    answer: "heredity",
  },
  {
    id: 125,
    category: "gen_education",
    difficulty: "medium",
    question: "_____ up! Or we'll be late.",
    choices: ["You hurry", "Be hurrying", "Hurry", "Hurry you"],
    answer: "Hurry",
  },
  {
    id: 126,
    category: "gen_education",
    difficulty: "hard",
    question: "Which of the following demonstrate sublimation?",
    choices: ["dry ice evaporating", "perspiration drying", "laundry drying", "steam forming water droplets"],
    answer: "laundry drying",
  },
  {
    id: 127,
    category: "gen_education",
    difficulty: "easy",
    question: "Ano ang salitang-ugat ng kanluran?",
    choices: ["kalan", "kanlong", "lunan", "lunod"],
    answer: "lunan",
  },
  {
    id: 128,
    category: "gen_education",
    difficulty: "medium",
    question: "A teacher wants to group her pupils into groups of 3 or 5 or 6. However, she found out that if she do that there will always be 1 pupil left. What is the least possible number of pupils in the class?",
    choices: ["81", "31", "21", "11"],
    answer: "31",
  },
  {
    id: 129,
    category: "gen_education",
    difficulty: "hard",
    question: "Ibigay ang aspekto ng pandiwa sa sumusunod na pangungusap. Mag-aral sa bahay ng mga araling ukol sa agham at teknolohiya.",
    choices: ["pawatas", "kontemplatibo", "imperpektibo", "perperktibo"],
    answer: "pawatas",
  },
  {
    id: 130,
    category: "gen_education",
    difficulty: "easy",
    question: "_____ taong masipag sa loob ng bulwagan.",
    choices: ["May", "Mayroong", "A at B", "Wala ang sagot sa mga pagpipilian."],
    answer: "May",
  },
  {
    id: 131,
    category: "gen_education",
    difficulty: "medium",
    question: "Who has greater moral responsibility and why? The lazy master teacher who does not teach well or the beginning teacher who is groping while she teaches and so does not teach well either.",
    choices: ["The master teacher, who is older and more experienced.", "The master teacher, who is expected to have more knowledge and freedom.", "Cannot be determined. Age, experience, or freedom does not necessarily make some one more or less morally responsible than the other.", "Both are equally morally responsible."],
    answer: "The master teacher, who is expected to have more knowledge and freedom.",
  },
  {
    id: 132,
    category: "gen_education",
    difficulty: "hard",
    question: "Which of the following is expressed clearly, effectively states the idea, and has no structural error?",
    choices: ["I would not want to be he.", "I would not want to be himself.", "I would not want to be themselves.", "I would not want to theirselves."],
    answer: "I would not want to be he.",
  },
  {
    id: 133,
    category: "gen_education",
    difficulty: "easy",
    question: "Alin and tamang babala sa pagtatapon ng basura?",
    choices: ["Gamitin and basurahan sa inyong bahay, huwag dito", "Dito and tambakan ng basura", "Huwag mag-tapon ng basura dito", "Huwag mag-ipon ng basura dito"],
    answer: "Huwag mag-tapon ng basura dito",
  },
  {
    id: 134,
    category: "gen_education",
    difficulty: "medium",
    question: "Which is the MOST important perceived need and problem of the Filipino family?",
    choices: ["Unemployment or financial problem", "Proneness to vices", "Over protectiveness of children", "Double standard on the roles of male and female"],
    answer: "Unemployment or financial problem",
  },
  {
    id: 135,
    category: "gen_education",
    difficulty: "hard",
    question: "Which of the following statements about living things is false?",
    choices: ["All living things use energy to function.", "All living things are composed of cells.", "All living things have a nervous system.", "All living things are capable of reproduction."],
    answer: "All living things have a nervous system.",
  },
  {
    id: 136,
    category: "gen_education",
    difficulty: "easy",
    question: 'Robert Frost wrote the poem "Acquainted with the Night" from which the stanza is taken: I have been one acquainted with the night. I have walked out in rain-back in rain. I have out walked the farthest city light The poet in the stanza talks of',
    choices: ["isolation and loneliness.", "happiness in having been acquainted with the night.", "joy getting out of the house.", "youthful delight playing in the rain."],
    answer: "isolation and loneliness.",
  },
  {
    id: 137,
    category: "gen_education",
    difficulty: "medium",
    question: "What form of government is characterized by the separation of powers?",
    choices: ["Parliamentary", "Presidential", "Aristocracy", "Monarchical"],
    answer: "Presidential",
  },
  {
    id: 138,
    category: "gen_education",
    difficulty: "hard",
    question: "Which is the BEST evidence that helium gas is lighter than air?",
    choices: ["Helium has the lowest boiling point of all elements.", "Helium atoms do not combine with other air atoms.", "Helium-filled balloons rise in air.", "By volume, helium makes up only 0.0005% of air."],
    answer: "Helium-filled balloons rise in air.",
  },
  {
    id: 139,
    category: "gen_education",
    difficulty: "easy",
    question: "I _____ get up at six o'clock this morning with much difficulty.",
    choices: ["could", "managed to", "can"],
    answer: "managed to",
  },
  {
    id: 140,
    category: "gen_education",
    difficulty: "medium",
    question: "One package is 100 pounds, and the other is 150 pounds. The weight of the second package is how many times that of the first?",
    choices: ["1½ times heavier", "½ as heavy", "none of these", "10 pounds heavier"],
    answer: "none of these",
  },
  {
    id: 141,
    category: "gen_education",
    difficulty: "hard",
    question: "Excursions are encouraged to allow participants to see places. All the 400 personnel fell ill. Doctors’ laboratory findings traced the cause to _____.",
    choices: ["congestion on the bus", "food poisoning", "excitement", "excessive fat"],
    answer: "food poisoning",
  },
  {
    id: 142,
    category: "gen_education",
    difficulty: "easy",
    question: "Which of the following facts support the Big Bang theory's explanation of the creation of the universe?",
    choices: ["The universe does not expand nor contract.", "The universe seldom expand.", "The universe will have background radiation.", "he universe has no beginning nor end."],
    answer: "The universe will have background radiation.",
  },
  {
    id: 143,
    category: "gen_education",
    difficulty: "medium",
    question: "In a university, the ratio of female professors to the male professors is 8:5. If there are 75 male professors, how many are female professors?",
    choices: ["120", "180", "225", "375/8"],
    answer: "120",
  },
  {
    id: 144,
    category: "gen_education",
    difficulty: "hard",
    question: "He_____ his leg while he _____ rugby.",
    choices: ["was breaking - played", "broke - was playing", "breaks - is playing"],
    answer: "broke - was playing",
  },
  {
    id: 145,
    category: "gen_education",
    difficulty: "easy",
    question: 'Someone wrote: "Environment relates to the profound relationship between matter, nature, and society, and in such a context, ICTs bring new ways of living in a more interconnected society, all of which reduces our dependency on matter and affects our relationship with nature." What does this convey?',
    choices: ["Environment and ICT are poles apart.", "ICT impacts on environment.", "Environment affects ICT.", "ICT brings us away from an interconnected society."],
    answer: "ICT impacts on environment.",
  },
  {
    id: 146,
    category: "gen_education",
    difficulty: "medium",
    question: "mantle",
    choices: ["the thickest layer of the Earth", "a process where one plate is forced under another", "the blanket of air surrounding the Earth", "describes how different types of rocks are formed"],
    answer: "the thickest layer of the Earth",
  },
  {
    id: 147,
    category: "gen_education",
    difficulty: "hard",
    question: '"Heto na, heto na, heto na, /wahh! Doo bidoo bidoo, bidoo, bidoo." Alin ang nabuong salita o tunog sa linya na nabuo ayon sa teoryang pooh-pooh?',
    choices: ["wahh", "heto", "na", "doo bidoo"],
    answer: "wahh",
  },
  {
    id: 148,
    category: "gen_education",
    difficulty: "easy",
    question: "A town that is located ______ is a location that should have most nearly twelve hours of daylight and twelve hours of darkness during December.",
    choices: ["halfway between the Equator and the South Pole", "close to the Equator", "close to the North Pole", "close to the South Pole"],
    answer: "close to the Equator",
  },
  {
    id: 149,
    category: "gen_education",
    difficulty: "medium",
    question: "And now for this evening’s main headline: Britain _____ another Olympic gold medal!",
    choices: ["had won", "wins", "won", "has won"],
    answer: "has won",
  },
  {
    id: 150,
    category: "gen_education",
    difficulty: "hard",
    question: "Charity begins at home. What illustrates this value?",
    choices: ["Millionaires send checks anonymously", "Patrons check out donations by the size of the advertisement", "Grandparents stay with the Home for the Aged. They are nuisance to modern families", "An ambassador in Jeddah shelters battered Filipino OCW’s and avoid social gatherings to be able to save food for these refugees"],
    answer: "An ambassador in Jeddah shelters battered Filipino OCW’s and avoid social gatherings to be able to save food for these refugees",
  },
  // Professional Education
  {
    id: 151,
    category: "professional",
    difficulty: "easy",
    question: "Which educational philosophy emphasizes the importance of student-centered learning?",
    choices: ["Progressivism", "Essentialism", "Perennialism", "Existentialism"],
    answer: "Progressivism",
    explanation: "Progressivism believes that education should focus on the whole child, rather than on the content or the teacher.",
  },
  {
    id: 152,
    category: "professional",
    difficulty: "medium",
    question: "What is the highest level in Bloom's Taxonomy (original version)?",
    choices: ["Evaluation", "Synthesis", "Analysis", "Application"],
    answer: "Evaluation",
    explanation: "In the original taxonomy, the levels are Knowledge, Comprehension, Application, Analysis, Synthesis, and Evaluation.",
  },
  {
    id: 153,
    category: "professional",
    difficulty: "hard",
    question: "What does the 'Zone of Proximal Development' (ZPD) by Lev Vygotsky refer to?",
    choices: [
        "The difference between what a learner can do without help and what they can achieve with guidance.",
        "The area in the classroom where students feel most comfortable.",
        "The level of knowledge a student is expected to have at a certain age.",
        "A method for assessing student intelligence."
    ],
    answer: "The difference between what a learner can do without help and what they can achieve with guidance.",
    explanation: "ZPD is a key concept in Vygotsky's sociocultural theory of learning.",
  },
  {
    id: 154,
    category: "professional",
    difficulty: "medium",
    question: "RA 7836 is also known as the...",
    choices: [
        "Philippine Teachers Professionalization Act of 1994",
        "Code of Ethics for Professional Teachers",
        "Magna Carta for Public School Teachers",
        "The Enhanced Basic Education Act of 2013"
    ],
    answer: "Philippine Teachers Professionalization Act of 1994",
    explanation: "This act strengthened the regulation and supervision of the practice of teaching in the Philippines.",
  },
  {
    id: 155,
    category: "professional",
    difficulty: "easy",
    question: "What type of assessment is conducted at the end of a unit to measure student learning?",
    choices: ["Summative Assessment", "Formative Assessment", "Diagnostic Assessment", "Authentic Assessment"],
    answer: "Summative Assessment",
    explanation: "Summative assessments are used to evaluate student learning, skill acquisition, and academic achievement at the conclusion of a defined instructional period.",
  },
  {
    id: 156,
    category: "professional",
    difficulty: "medium",
    question: "Which learning theory suggests that people learn from one another, via observation, imitation, and modeling?",
    choices: ["Social Learning Theory", "Behaviorism", "Cognitivism", "Constructivism"],
    answer: "Social Learning Theory",
    explanation: "Albert Bandura's Social Learning Theory posits that learning is a cognitive process that takes place in a social context.",
  },
  {
    id: 157,
    category: "professional",
    difficulty: "easy",
    question: "Which of the following is a primary role of a teacher in a constructivist classroom?",
    choices: ["Facilitator", "Lecturer", "Instructor", "Dictator"],
    answer: "Facilitator",
    explanation: "In constructivism, the teacher acts as a facilitator who guides students as they construct their own knowledge.",
  },
  {
    id: 158,
    category: "professional",
    difficulty: "hard",
    question: "A teacher uses a portfolio to assess a student's progress over a period. What type of assessment is this?",
    choices: ["Authentic Assessment", "Summative Assessment", "Norm-referenced Assessment", "Criterion-referenced Assessment"],
    answer: "Authentic Assessment",
    explanation: "Authentic assessment involves tasks that are relevant to the students' lives and experiences, such as creating a portfolio.",
  }
];

export const pets: Pet[] = [
    { name: "Pet Rock", unlock_criteria: "1-day streak", streak_req: 1, image: "https://placehold.co/200x200", hint: "rock stone" },
    { name: "Goldfish", unlock_criteria: "3-day streak", streak_req: 3, image: "https://placehold.co/200x200", hint: "goldfish fishbowl" },
    { name: "Turtle", unlock_criteria: "7-day streak", streak_req: 7, image: "https://placehold.co/200x200", hint: "sea turtle" },
    { name: "Corgi", unlock_criteria: "14-day streak", streak_req: 14, image: "https://placehold.co/200x200", hint: "cute dog" },
    { name: "Owl", unlock_criteria: "21-day streak", streak_req: 21, image: "https://placehold.co/200x200", hint: "wise owl" },
    { name: "Panda", unlock_criteria: "30-day streak", streak_req: 30, image: "https://placehold.co/200x200", hint: "panda eating" },
    { name: "T-Rex", unlock_criteria: "50-day streak", streak_req: 50, image: "https://placehold.co/200x200", hint: "dinosaur rex" },
    { name: "Dragon", unlock_criteria: "75-day streak", streak_req: 75, image: "https://placehold.co/200x200", hint: "fantasy dragon" },
    { name: "Phoenix", unlock_criteria: "100-day streak", streak_req: 100, image: "https://placehold.co/200x200", hint: "fire bird" },
];
