
import type { ReviewArticle } from './types';

export const reviewArticles: ReviewArticle[] = [
    {
        slug: "child-adolescent-development",
        title: "Child and Adolescent Development",
        category: "profed",
        description: "An overview of the physical, cognitive, and socio-emotional development of children and adolescents.",
        type: "Article",
        readingTime: 15,
        difficulty: "easy",
    },
    {
        slug: "facilitating-learning",
        title: "Facilitating Learner-Centered Teaching",
        category: "profed",
        description: "Explore various theories and strategies for creating a learner-centered classroom environment.",
        type: "Article",
        readingTime: 20,
        difficulty: "medium",
    },
    {
        slug: "assessment-of-learning-1",
        title: "Assessment of Learning 1: Principles",
        category: "profed",
        description: "Fundamental concepts, principles, and practices in educational assessment.",
        type: "Mixed",
        readingTime: 25,
        difficulty: "medium",
    },
    {
        slug: "rizals-life-works",
        title: "Rizal's Life and Works",
        category: "gened",
        description: "A comprehensive review of the life, works, and writings of the national hero, Dr. Jose Rizal.",
        type: "Article",
        readingTime: 30,
        difficulty: "medium",
    },
    {
        slug: "philippine-history",
        title: "Foundations of Philippine History",
        category: "gened",
        description: "Key events, figures, and periods that shaped the history of the Philippines.",
        type: "Video",
        readingTime: 18,
        difficulty: "easy",
    },
    {
        slug: "teaching-profession",
        title: "The Teaching Profession",
        category: "profed",
        description: "Covers the code of ethics, rights, and responsibilities of a professional teacher in the Philippines.",
        type: "Article",
        readingTime: 15,
        difficulty: "easy",
    },
     {
        slug: "purposive-communication",
        title: "Purposive Communication",
        category: "gened",
        description: "Principles of effective communication in various multicultural and professional contexts.",
        type: "Article",
        readingTime: 20,
        difficulty: "easy",
    },
    {
        slug: "the-child-as-a-learner",
        title: "The Child as a Learner",
        category: "profed",
        description: "Deep dive into different learning theories including behaviorism, cognitivism, and constructivism.",
        type: "Article",
        readingTime: 25,
        difficulty: "hard",
    },
    {
        slug: "science-tech-society",
        title: "Science, Technology, and Society",
        category: "gened",
        description: "Examines the interactions between science, technology, and social, cultural, political, and economic systems.",
        type: "Mixed",
        readingTime: 22,
        difficulty: "medium",
    },
];
