
// This file is auto-generated by the Firebase CLI.
// Do not edit it manually.
export const firebaseConfig = {
  apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  authDomain: "letreview-1a23b.firebaseapp.com",
  projectId: "letreview-1a23b",
  storageBucket: "letreview-1a23b.appspot.com",
  messagingSenderId: "123456789012",
  appId: "1:123456789012:web:1234567890abcdef123456",
  measurementId: "G-XXXXXXXXXX"
};
